apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-dev-monitoring
  namespace: argocd
spec:
  project: eks-dev-monitoring

  source:
    repoURL: https://github.com/ffreville/argo-test.git
    targetRevision: HEAD
    path: eks-dev/monitoring
  destination: 
    server: https://kubernetes.default.svc
    namespace: fred-monitoring

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
